/*
 * Inputs
 */
variable "ssh_key_name_prefix" {
  description = "Key name prefix for ssh rsa public key"
  default = "terraform-"
}

variable "ssh_public_key_path" {
  description = "Path to ssh rsa public key"
  default = "~/.ssh/id_rsa.pub"
}

variable "iam_role_name" {
  description = "The name of the IAM Role."
}

variable "iam_role_path" {
  description = "The path to the IAM Role."
  default     = "/"
}

variable "iam_role_description" {
  description = "The description of the IAM Role."
  default     = "This IAM Role generated by Terraform."
}

variable "iam_role_force_detach_policies" {
  description = "Forcibly detach the policy of the role."
  default     = false
}

variable "iam_role_policy_arn" {
  description = "Attache the policies to the IAM Role."
  type        = "list"
}

/**
 * role-policy
 */
module "key-pair-default" {
    source          = "Smartbrood/key-pair/aws"
    key_name_prefix = "${var.ssh_key_name_prefix}"
    public_key_path = "${var.ssh_public_key_path}"
}

module "ec2_iam_role_default" {
   source      = "Smartbrood/ec2-iam-role/aws"

   name        = "${var.iam_role_name}"
   policy_arn  = "${var.iam_role_policy_arn}"

   path        = "${var.iam_role_path}"
   description = "${var.iam_role_description}"

   force_detach_policies = "${var.iam_role_force_detach_policies}"
}

/*
 * Outputs
 */

output "ssh_key_name" {
  description = "Default SSH key name for EC2"
  value       = "${module.key-pair-default.key_name}"
}

output "iam_instance_profile" {
  description = "Default IAM instance profile for EC2"
  value       = "${module.ec2_iam_role_default.profile_name}"
}

